### ISSUE TITLE
Providing dataset

### ISSUE THREAD

**Issue by FuTSy13** [m-bain/frozen-in-time#1]
Hello! Thank you for the very interesting work. Could you please provide the WebVid-2M data set?

**Comment by m-bain** [comment]
Hi,

We are aiming to release the data urls and cleaned captions soon (ETA ~1-2 months).

Best,
Max

**Comment by m-bain** [comment]
Webvid data can be found here
https://github.com/m-bain/webvid
https://m-bain.github.io/webvid-dataset/
