### ISSUE TITLE
The provided Pillow package doesn't support WEBP images

### ISSUE THREAD

**Issue by bryant1410** [m-bain/frozen-in-time#10]
A warning is shown during training with CC3M data saying so. See: https://github.com/ContinuumIO/anaconda-issues/issues/10737 So I guess these images are going to be skipped during training?

**Comment by skupr-anaconda** [comment]
Try with conda install pillow==8.3.1
It supports WEBP images

**Comment by m-bain** [comment]
Good spot, these wouldve been treated as blank images during training, I upgraded PIL and now it works. This ought to improve performance so I'll retrain when I have the chance 408ea9935d48850e2a9f8302688a8ea695611ab4

**Comment by bryant1410** [comment]
Be careful that now 408ea99 uses a `torchvision` package for a previous version of CUDA. I believe you need to re-include the options to use the correct version of CUDA for it.

**Comment by bryant1410** [comment]
I saw you added another commit adding the suffix. Also, remember the flag `--find-links`! Otherwise, it won't work.

**Comment by m-bain** [comment]
Added, thanks for the reminder!
