### ISSUE TITLE
Config for the method trained on CC3M

### ISSUE THREAD

**Issue by bryant1410** [m-bain/frozen-in-time#11]
I was wondering if you could provide the config used in the paper to train only on CC3M. Is it exactly like the one CC3M+WebVid but removing the WebVid part?

**Comment by m-bain** [comment]
Yes exactly, I added it for completeness 67306e49b3ffccf6113b827ae3935dd2c4c11fb0

**Comment by bryant1410** [comment]
BTW, what does the "i2k" mean at the end of some config file names?

**Comment by m-bain** [comment]
Hey, i2k means imagenet-21k initialisation. We start with a pretraining image ViT, then inflate this to video. There are some video transformers now which don't require imagenet intialisation (MViT), albeit with longer training times, will look into adding these soon.
