### ISSUE TITLE
data and code release

### ISSUE THREAD

**Issue by junchen14** [m-bain/frozen-in-time#2]
it is nice to read your paper and I find this work is very interesting to me

I am wondering when will you release your data and code?

**Comment by m-bain** [comment]
Hi, sorry for the delay.
Code is being released iteratively: currently the code lets you train on MSRVTT with imagenet initialisation.
WebVid data will be released soon, I am hoping 1 month.

**Comment by m-bain** [comment]
Webvid data can be found here.
https://github.com/m-bain/webvid
https://m-bain.github.io/webvid-dataset/
