### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by zvr** [m-bain/frozen-in-time#44]
Hi @m-bain and @bryant1410 
Many thanks for this work!

Can you please specify which license it is released under? As it currently is, without any mention, it cannot be legally used by anyone for anything...

The original `pytorch-template` is under [MIT](https://github.com/victoresque/pytorch-template/blob/master/LICENSE), so I guess this would be an acceptable choice. But of course it's up to you to decide.

**Comment by m-bain** [comment]
oops, thanks for pointing this out -- have added MIT license.
