### ISSUE TITLE
How about initializing parameters with CLIP model

### ISSUE THREAD

**Issue by realTaki** [m-bain/frozen-in-time#46]
I think SpaceTimeTransformer can use to extend the CLIP model to process videos. 

For example, the 'openai/clip-vit-base-patch32' is based on a text_transformer and a ViT backbone. 
I am trying this, the text_model part can be used directly, but the ViT part is different in variables' names and seems hard to align.

**Comment by m-bain** [comment]
Hi, yes I was looking into this as an extension to the work but the CLIP ViT is a much more different implementation.

I found even with timesformer implementation I get slightly different outputs at initialisation compare to the imagenet model.

Our latest work on adapting CLIP for video modelling: https://arxiv.org/abs/2205.08508 seems to suggest that minimal deviation from clip embedding gives best performance. I think a major reason is that the downstream video datasets are quite small and so you end up overfitting and catastrophic forgetting of the highly general CLIP image-level representation.

Also text-to-video retrieval seems to not require much temporal modelling in general -- I think if you evaluate on SS-V2 then you might do better (CLIP does really bad on this).
