### ISSUE TITLE
config about Paper Result

### ISSUE THREAD

**Issue by shufangxun** [m-bain/frozen-in-time#50]
run the test script
`test.py --resume PATH_TO_FINETUNED_CHECKPOINT --sliding_window_stride 12`

the sliding window stride argument adds temporal averaging over multiple frame samples :)

_Originally posted by @m-bain in https://github.com/m-bain/frozen-in-time/issues/41#issuecomment-1079998817_

**Comment by shufangxun** [comment]
hello, I want to know whether the result in the paper comes from sliding_window_stride=12 or =1？

**Comment by m-bain** [comment]
Hi, I use 12 in the paper, I think there is diminishing returns with temporal averaging (like 0.1 R@1), let me know if you find difference
