### ISSUE TITLE
Code/template for the demo?

### ISSUE THREAD

**Issue by scottfleming** [m-bain/frozen-in-time#51]
Awesome project and great work! I was wondering if the code for the video search demo is available or could be made available? Would be very nice to have even just for debugging the process of fine tuning your model on a different dataset.

**Comment by m-bain** [comment]
Hi,
Thanks for the request, I'll ask my supervisors what they think. I think currently the code provides scripts on extracting features and creating a FAISS index.

I think the final steps are 
(i) running inference on the text queries via the text encoder and finding the NN videos in the FAISS index
(ii) visualising the top-k videos on a webpage (for webvid you can do this by embedding the corresponding video url in the csv file).

**Comment by scottfleming** [comment]
Totally, that's already really helpful (the scripts for extracting features and creating the FAISS index), so thank you for that. As someone with limited web dev experience, having the backbone javascript/html for locally hosting an interactive webpage to query for my own purposes would also be very helpful, but I understand that you may be constrained by the powers that be.

**Comment by m-bain** [comment]
Mm yeah tbh if its just for local visualisation you can just write a python scripts which takes the top-k NN results in the FAISS and writes a webpage which embeds the list of videos. No need for javascript or anything
`<video src="path/to/ith_topk_video.mp4">`
(although this isn't as seamless as a live interactive search query). You could look into using Django which is web dev in python and should be fairly quick to make this locally.

**Comment by 1980x** [comment]
Hi,
Will it be possible to share the demo search code? 

Thanks
