### ISSUE TITLE
CC3M dataset broken

### ISSUE THREAD

**Issue by shufangxun** [m-bain/frozen-in-time#52]
hello, I find that a large portion of CC3M is missing due to broken url, and the dataset size shrinks to 1.9M. I want to ask the size of CC3M you used or do you have full link to download it?

**Comment by m-bain** [comment]
Hmm yeah 1.9M is a big drop, that's unfortunate. My academic lab had it downloaded a while ago (before I started the project), I calculated 2.92M valid images. Unfortunately I don't have a mirror to share, sorry!
