### ISSUE TITLE
pre-process mp4

### ISSUE THREAD

**Issue by nattikahana** [m-bain/frozen-in-time#55]
Hi I would like to know what is the best way that you recommend to pre-process a mp4 video so it will work best with your project.

**Comment by m-bain** [comment]
Hi, input resolution to model is 224, but random crop during training so mp4's with shortest side as 256px is good!
For fps, it again will be a tradeoff between perf. and speed -- pretraining on webvid is so big it doesnt matter (1fps) is good. For finetuning original fps (~20+ fps is good)
