### ISSUE TITLE
Question about pretrained models?

### ISSUE THREAD

**Issue by valeriomieuli** [m-bain/frozen-in-time#56]
Hello , I have downloaded the .tar file with the pretrained models but I can not understand how they are organised.

From the .tar archive I extracted something like

data
data.pkl
version

It seems that

- data is a directory with many binary files in it
- data.pkl - not understood
- version - text file with "3" written there

Can you please help to understand

- What should the content of that .tar file be?
- Which pretrained model's weights are actually provided ? (i.e. pre train  / fine tune on dataset X) ?

Thanks for your effort and congrats for the brilliant innovation !

**Comment by m-bain** [comment]
Hi, don't untar the file, it should be loaded directly in torch in the directory where the repository is installed.
`torch.load("$path_to_tar file")`
These are just the pretrained weights for the model trained on CC3M + WebVid (4 frames).
